#: import MeshLinePlot kivy.garden.graph.MeshLinePlot
<Runner>:
	#Handling the gesture event.
	on_two_left_to_right_line:   app.root.transition.direction = 'right'
	on_two_right_to_left_line:  app.root.transition.direction = 'left'
	on_two_down_to_up_line:  app.root.transition.direction = 'up'
# Layout the Screen Manager
<CoffeeScreenManager>:
	id: manager
	MenuScreen:	
	CoffeeScreen:
	ControlScreen:

# Layout the Menu screen
<MenuScreen>:
	name: 'menu'

	BoxLayout:
		orientation: 'vertical'
		Label:
			text:'Welcome to the Menu!'
			font_size:50
		BoxLayout:
			
			Button:
				text:'Coffee Maker'
				font_size:30
				on_release:app.root.current ='coffee'

# Layout the NCP screen		

<CoffeeScreen>:
	name:'coffee'
	Runner: 
		on_two_down_to_up_line: app.root.current = 'menu'
		on_two_right_to_left_line: app.root.current = 'control'
		
	BoxLayout:
		orientation: 'vertical'
		Label: 
			text: 'Coffee Status'
			font_size:45
		
		GridLayout:
			rows:2
			cols:6
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water level'
					font_size:30
				Light_indicator:
					id:water_lv_lights
					num:3
					color1:'red'
					color2:'green'
					color3:'red'
					pos_l1: 60,40
					pos_l2: 135,40
					pos_l3: 210,40
					setting_on: False
					label_on:True
					l1_label:"Under min"
					l3_label:"Over Max"
					bol2:True
					size_lights:40,40

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Temp'
					font_size:30
				Label:
					text: "Some #"
				BoxLayout:
					CheckBox:
						group:"temp"
						active:True
					Label:
						text:"F"
						halign: 'left'
					CheckBox:
						group:"temp"
					Label:
						text:"C"
						
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Altitude Mode'
					font_size:30
				Light_indicator:
					id:altitude_lights
					num:1
					color1:'green'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"On"
					size_lights:40,40

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Air Pump'
					font_size:30
				Light_indicator:
					id:air_pump_lights
					num:1
					color1:'green'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"On"
					size_lights:40,40
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Pump'
					font_size:30
				Light_indicator:
					id:water_pump_lights
					num:1
					color1:'green'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"On"
					size_lights:40,40
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Pumping Volume'
					font_size:30
				Label:
					text:"some #"

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Door'
					font_size:30
				Light_indicator:
					id:pod_door_lights
					num:1
					color1:'red'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"Open"
					size_lights:40,40
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Present?'
					font_size:30
				Light_indicator:
					id:pod_door_lights
					num:1
					color1:'red'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"Missing"
					size_lights:40,40
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Color'
					font_size:30
				Label:
					text: "Some Color"

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Carafe Present?'
					font_size:30
				Light_indicator:
					id:carafe_lights
					num:1
					color1:'red'
					pos_l1: 135,40
					setting_on: False
					label_on:True
					l1_label:"Missing"
					size_lights:40,40
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'LED Status'
					font_size:30
				Light_indicator:
					id:led_lights
					num:1
					color1:'green'
					pos_l1: 135,40
					setting_on: False
					label_on:False
					size_lights:40,40					

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Home Sensor'
					font_size:30
				Label:
					text:"???????"


			
		BoxLayout:
			BoxLayout:
				Button:
					size_hint: None, None
					size: 200,100
					text: 'Brew!'
					font_size: 30
				Button:
					size_hint: None, None
					size: 200,100
					text: 'Stop!'
					font_size: 30
					canvas:
						Color:
							rgba: 1,0,0,0.4
						Rectangle:
							pos:self.pos
							size: self.size


<ControlScreen>:
	name:'control'
	Runner: 
		on_two_down_to_up_line: app.root.current = 'menu'
		on_two_left_to_right_line: app.root.current = 'coffee'

	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			size_hint: 1,0.5
			Label: 
				text: 'Coffee Control'
				font_size:45
		
		GridLayout:
			rows:2
			cols:6
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water level'
					font_size:30
				BoxLayout:
					Label:
						text:""
					Knob:
						id:water_lv_knob
						size: 100, 100
						min: 0
						max: 100
						step: 1
						value: 0  # Default position of knob.
						knobimg_source: "/home/nagato/.kivy/garden/garden.knob/img/knob_metal.png"  # Knob texture
						show_label: True  # Show central label
						show_marker: False  # Do not show surrounding marker
					Label:
						text:str(water_lv_knob.value)

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Temp'
					font_size:30
				Label:
					text: "Some #"
						
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Altitude Mode'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"On"
					Button:
						size_hint:None,None
						size:100,100
						text:"Off"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Air Pump'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"On"
					Button:
						size_hint:None,None
						size:100,100
						text:"Off"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Pump'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"On"
					Button:
						size_hint:None,None
						size:100,100
						text:"Off"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Water Pumping Volume'
					font_size:30
				Spinner:
					text: "4 oz"
					values: '4 oz','6 oz','8 oz', '10 oz', '12 oz'

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Door'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"Open"
					Button:
						size_hint:None,None
						size:100,100
						text:"Closed"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Present?'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"Present"
					Button:
						size_hint:None,None
						size:100,100
						text:"Missing"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Pod Color'
					font_size:30
				Label:
					text: "Some Color"

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Carafe Present?'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"Present"
					Button:
						size_hint:None,None
						size:100,100
						text:"Missing"
			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'LED Status'
					font_size:30
				BoxLayout:
					Button:
						size_hint:None,None
						size:100,100
						text:"Off"
					Button:
						size_hint:None,None
						size:100,100
						text:"Flashing"	
					Button:
						size_hint:None,None
						size:100,100
						text:"On"					

			BoxLayout:
				orientation: 'vertical'
				Label:
					text:'Home Sensor'
					font_size:30
				Label:
					text:"???????"


			


